// Copyright (c) 2025 Ilarion. All rights reserved.
//
// HarmonyPatches/LoadTransporters/WorkGiver_FloatMenuOption_Patch.cs
using HarmonyLib;
using RimWorld;
using Verse;

namespace BulkLoadForTransporters.HarmonyPatches.LoadTransporters
{
    /// <summary>
    /// Patches `FloatMenuOptionProvider_WorkGivers.GetWorkGiverOption` to specifically suppress the option generated by `WorkGiver_LoadTransporters`.
    /// </summary>
    [HarmonyPatch(typeof(FloatMenuOptionProvider_WorkGivers), "GetWorkGiverOption")]
    public static class FloatMenuOption_LoadTransporters_Patch
    {
        public static bool Prepare()
        {
            return LoadedModManager.GetMod<Core.BulkLoadForTransportersMod>().GetSettings<Core.Settings>().enableBulkLoadTransporters;
        }

        /// <summary>
        /// A Prefix that identifies when the game is trying to create an option for the vanilla `WorkGiver_LoadTransporters` and stops it.
        /// </summary>
        [HarmonyPrefix]
        public static bool Prefix(WorkGiverDef workGiver)
        {
            if (workGiver.giverClass == typeof(WorkGiver_LoadTransporters))
            {
                return false; // false = skip the original method
            }

            return true; 
        }
    }
}